#!/bin/sh
# Xcode Cloud runs this immediately after cloning the repository.
#
# Walkful's Xcode project is GENERATED by XcodeGen from project.yml and is
# git-ignored (project.yml is the source of truth — see README/CLAUDE.md). A
# fresh Xcode Cloud clone therefore has no Walkful.xcodeproj to build, so we
# regenerate it here. This also recreates the managed Info.plist files (also
# git-ignored). After this runs, Xcode Cloud can build the shared "Walkful"
# scheme normally.

set -e

export HOMEBREW_NO_AUTO_UPDATE=1

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "ci_post_clone: installing XcodeGen via Homebrew"
  brew install xcodegen
fi

REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$REPO"

echo "ci_post_clone: generating the Xcode project from project.yml"
xcodegen generate

echo "ci_post_clone: done — generated $(ls -d *.xcodeproj)"
