#!/bin/sh
# Xcode Cloud runs this immediately after cloning the repository.
#
# Walkful's Xcode project is GENERATED by XcodeGen from project.yml and is
# git-ignored (project.yml is the source of truth — see README/CLAUDE.md). A
# fresh Xcode Cloud clone therefore has no Walkful.xcodeproj to build, so we
# regenerate it here. This also recreates the managed Info.plist files (also
# git-ignored). After this runs, Xcode Cloud can build the shared "Walkful"
# scheme normally.

set -e

export HOMEBREW_NO_AUTO_UPDATE=1

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "ci_post_clone: installing XcodeGen via Homebrew"
  brew install xcodegen
fi

REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$REPO"

echo "ci_post_clone: generating the Xcode project from project.yml"
xcodegen generate

# Xcode Cloud's "Resolve package dependencies" step runs with automatic
# resolution DISABLED and requires a committed Package.resolved — which we
# can't commit because the .xcodeproj is generated/git-ignored. Resolve here
# (auto-resolution IS allowed in this script) so the workspace has a
# Package.resolved before that step runs.
echo "ci_post_clone: pre-resolving Swift package dependencies"
xcodebuild -resolvePackageDependencies -project Walkful.xcodeproj -scheme Walkful

echo "ci_post_clone: done — generated $(ls -d *.xcodeproj); Package.resolved: $(ls Walkful.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved 2>/dev/null || echo MISSING)"
