#!/bin/sh
# Xcode Cloud runs this immediately after cloning the repository.
#
# Walkful's Xcode project is GENERATED by XcodeGen from project.yml and is
# git-ignored (project.yml is the source of truth — see README/CLAUDE.md). A
# fresh Xcode Cloud clone therefore has no Walkful.xcodeproj to build, so we
# regenerate it here. This also recreates the managed Info.plist files (also
# git-ignored). After this runs, Xcode Cloud can build the shared "Walkful"
# scheme normally.

set -e

export HOMEBREW_NO_AUTO_UPDATE=1

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "ci_post_clone: installing XcodeGen via Homebrew"
  brew install xcodegen
fi

REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$REPO"

echo "ci_post_clone: generating the Xcode project from project.yml"
xcodegen generate

# Xcode Cloud disables automatic SwiftPM resolution environment-wide (even a
# manual `xcodebuild -resolvePackageDependencies` is refused) and requires a
# Package.resolved at
# Walkful.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved.
# We can't commit it there (the .xcodeproj is generated/git-ignored), so we keep
# a checked-in copy at ci_scripts/Package.resolved and drop it into place after
# generating the project. Xcode Cloud then fetches exactly the pinned versions.
# NOTE: if you change SPM dependencies in project.yml, regenerate this file:
#   xcodegen generate && xcodebuild -resolvePackageDependencies -project Walkful.xcodeproj -scheme Walkful
#   cp Walkful.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved ci_scripts/Package.resolved
SWIFTPM_DIR="Walkful.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$SWIFTPM_DIR"
cp "$(dirname "$0")/Package.resolved" "$SWIFTPM_DIR/Package.resolved"

echo "ci_post_clone: done — generated $(ls -d *.xcodeproj); Package.resolved in place: $(ls "$SWIFTPM_DIR/Package.resolved" 2>/dev/null || echo MISSING)"
